In [102]:
from keras.preprocessing.text import Tokenizer
import nltk
from nltk.tokenize import word_tokenize
import numpy as np
import re
from keras.utils import to_categorical


In [103]:
test="भारतमा एकैदिन यति धेरै संख्यामा संक्रमण पुष्टि भएको यो पहिलो पटक हो  योसँगै भारतमा कोरोना भाइरसबाट संक्रमित हुनेको संख्या ३८ लाख ५३ हजार ४ सय ४ पुगेको छ त्यस्तै पछिल्लो २४ घण्टामा कोरोनाबाट थप एक हजार ४३ जनाको मृत्यु भएको छ  अहिलेसम्म भारतमा कोरोना संक्रमणबाट मृत्यु हुनेको संख्या ६७ हजार ३ सय ७६ पुगेको छ कोरोना संक्रमणका हिसाबले भारत विश्वमै तेस्रो प्रभावित मुलुक हो कोरोना महामारीबाट सबैभन्दा बढी प्रभावित अमेरिकामा बिहीबार बिहानसम्म ६१ लाख ११ हजारभन्दा बढीमा संक्रमण पुष्टि भएको छ अमेरिकामा हालसम्म करिब एक लाख ८५ हजारको मृत्यु भइसकेको छ भने २२ लाखभन्दा बढी निको भएका छन् आज बिहीबार पनि देशका विभिन्न स्थानमा हल्कादेखि भारीसम्म वर्षा हुने सम्भावना रहेको मौसम पूर्वानुमान महाशाखाले जनाएको छ महाशाखाका अनुसार दिउँसो देशभर सामान्यतया बदली रही केही स्थानमा मेघगर्जन/चट्याङसहित हल्कादेखि मध्यम वर्षाको सम्भावना छ बागमती, गण्डकी, प्रदेश ५, कर्णाली र सुदूरपश्चिम प्रदेशका एक वा दुई स्थानमा भने भारी वर्षाको समेत सम्भावना छ यस्तै राति पनि देशभर सामान्यतया बदली रही थोरै स्थानमा मेघगर्जन/चट्याङसहित हल्कादेखि मध्यम वर्षाको सम्भावना छ बागमती, गण्डकी, सुदूरपश्चिम र कर्णाली प्रदेशका एक वा दुई स्थानमा भने भारी वर्षाको समेत सम्भावना रहेको महाशाखाले बिहीबार बिहान जारी गरेको मौसम पूर्वानुमान बुलेटिनमा उल्लेख छ आगामी २४ घण्टा (बिहीबार बिहान ६ बजेदेखि शुक्रबार बिहान ६ बजेसम्म) का लागि चेतावनी तथा परामर्श जारी गर्दै महाशाखाले भनेको छ बागमती, गण्डकी, प्रदेश ५, कर्णाली र सुदूरपश्चिम प्रदेशका एक वा दुई स्थानमा भारी वर्षाको सम्भावना रहेकाले आवश्यक सतर्कता अपनाउन हुन अनुरोध छ"

# Data Cleaning

In [ ]:
''' Return the List of word of the string variable "cleaned".Here list contain repeative words'''


tokens = word_tokenize(test)
print(len(tokens))
print(tokens , end= " ") #print on same line

242
['भारतमा', 'एकैदिन', 'यति', 'धेरै', 'संख्यामा', 'संक्रमण', 'पुष्टि', 'भएको', 'यो', 'पहिलो', 'पटक', 'हो', 'योसँगै', 'भारतमा', 'कोरोना', 'भाइरसबाट', 'संक्रमित', 'हुनेको', 'संख्या', '३८', 'लाख', '५३', 'हजार', '४', 'सय', '४', 'पुगेको', 'छ', 'त्यस्तै', 'पछिल्लो', '२४', 'घण्टामा', 'कोरोनाबाट', 'थप', 'एक', 'हजार', '४३', 'जनाको', 'मृत्यु', 'भएको', 'छ', 'अहिलेसम्म', 'भारतमा', 'कोरोना', 'संक्रमणबाट', 'मृत्यु', 'हुनेको', 'संख्या', '६७', 'हजार', '३', 'सय', '७६', 'पुगेको', 'छ', 'कोरोना', 'संक्रमणका', 'हिसाबले', 'भारत', 'विश्वमै', 'तेस्रो', 'प्रभावित', 'मुलुक', 'हो', 'कोरोना', 'महामारीबाट', 'सबैभन्दा', 'बढी', 'प्रभावित', 'अमेरिकामा', 'बिहीबार', 'बिहानसम्म', '६१', 'लाख', '११', 'हजारभन्दा', 'बढीमा', 'संक्रमण', 'पुष्टि', 'भएको', 'छ', 'अमेरिकामा', 'हालसम्म', 'करिब', 'एक', 'लाख', '८५', 'हजारको', 'मृत्यु', 'भइसकेको', 'छ', 'भने', '२२', 'लाखभन्दा', 'बढी', 'निको', 'भएका', 'छन्', 'आज', 'बिहीबार', 'पनि', 'देशका', 'विभिन्न', 'स्थानमा', 'हल्कादेखि', 'भारीसम्म', 'वर्षा', 'हुने', 'सम्भावना', 'रहेको', 'मौसम', '

In [104]:
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [105]:
def stemword(word):
		x = re.findall(r'^((.*?)(लाई|ले|लागि|बाट|देखि|को|की|का|मा|माथि|कै|हरु|मै|न्ने|सँग))$', word)
		if x:
			y = re.findall(r'^((.*?)(लाई|ले|लागि|बाट|देखि|को|की|का|मा|माथि|कै|हरु|मै|न्ने|सँग))$', x[0][1])
			if y:
				return y[0][1]
			else:
				return x[0][1]
		else:
			return word

In [ ]:
stemword('भारतमा')

'भारत'

In [ ]:
re.findall(r'^((.*?)(लाई|ले|लागि|बाट|देखि|को|की|का|मा|माथि|कै|हरु|मै|न्ने|सँग))$', 'भारतमा')

[('भारतमा', 'भारत', 'मा')]

In [ ]:
re.findall(r'^((.*?)(लाई|ले|लागि|बाट|देखि|को|की|का|मा|माथि|कै|हरु|मै|न्ने|सँग))$', 'भारतमा')[0]

('भारतमा', 'भारत', 'मा')

In [ ]:
re.findall(r'^((.*?)(लाई|ले|लागि|बाट|देखि|को|की|का|मा|माथि|कै|हरु|मै|न्ने|सँग))$', 'भारतमा')[0][1]


'भारत'

In [ ]:
re.findall(r'^((.*?)(लाई|ले|लागि|बाट|देखि|को|की|का|मा|माथि|कै|हरु|मै|न्ने|सँग))$', 'भारतम')

[]

In [106]:
nepali_num = re.compile(r'(०|१|२|३|४|५|६|७|८|९)+')

token= [token for token in tokens if  not nepali_num.match(token)]

exclude = string.punctuation
# exclude = set(string.punctuation) # Set of all special characters
# Remove all the special characters
tokens=[stemword(ch) for ch in token if ch not in exclude]
len(token)

214

In [141]:
tokens

['भारत',
 'एकैदिन',
 'यति',
 'धेरै',
 'संख्या',
 'संक्रमण',
 'पुष्टि',
 'भए',
 'यो',
 'पहिलो',
 'पटक',
 'हो',
 'योसँगै',
 'भारत',
 'कोरोना',
 'भाइरस',
 'संक्रमित',
 'हुने',
 'संख्या',
 'लाख',
 'हजार',
 'सय',
 'पुगे',
 'छ',
 'त्यस्तै',
 'पछिल्लो',
 'घण्टा',
 'कोरोना',
 'थप',
 'एक',
 'हजार',
 'जना',
 'मृत्यु',
 'भए',
 'छ',
 'अहिलेसम्म',
 'भारत',
 'कोरोना',
 'संक्रमण',
 'मृत्यु',
 'हुने',
 'संख्या',
 'हजार',
 'सय',
 'पुगे',
 'छ',
 'कोरोना',
 'संक्रमण',
 'हिसाब',
 'भारत',
 'विश्व',
 'तेस्रो',
 'प्रभावित',
 'मुलुक',
 'हो',
 'कोरोना',
 'महामारी',
 'सबैभन्दा',
 'बढी',
 'प्रभावित',
 'अमेरि',
 'बिहीबार',
 'बिहानसम्म',
 'लाख',
 'हजारभन्दा',
 'बढी',
 'संक्रमण',
 'पुष्टि',
 'भए',
 'छ',
 'अमेरि',
 'हालसम्म',
 'करिब',
 'एक',
 'लाख',
 'हजार',
 'मृत्यु',
 'भइसके',
 'छ',
 'भने',
 'लाखभन्दा',
 'बढी',
 'नि',
 'भए',
 'छन्',
 'आज',
 'बिहीबार',
 'पनि',
 'देश',
 'विभिन्न',
 'स्थान',
 'हल्',
 'भारीसम्म',
 'वर्षा',
 'हुने',
 'सम्भावना',
 'रहे',
 'मौसम',
 'पूर्वानुमान',
 'महाशाखा',
 'जनाए',
 'छ',
 'महाशाखा',
 '

In [ ]:
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [107]:
'''
  train_len = 3+1:
  Here 3 refer to No of Input Words we take and 1 refer to the Output words.
'''
train_len = 3+1
text_sequences = []
for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i]
    text_sequences.append(seq)

text_sequences

[['भारत', 'एकैदिन', 'यति', 'धेरै'],
 ['एकैदिन', 'यति', 'धेरै', 'संख्या'],
 ['यति', 'धेरै', 'संख्या', 'संक्रमण'],
 ['धेरै', 'संख्या', 'संक्रमण', 'पुष्टि'],
 ['संख्या', 'संक्रमण', 'पुष्टि', 'भए'],
 ['संक्रमण', 'पुष्टि', 'भए', 'यो'],
 ['पुष्टि', 'भए', 'यो', 'पहिलो'],
 ['भए', 'यो', 'पहिलो', 'पटक'],
 ['यो', 'पहिलो', 'पटक', 'हो'],
 ['पहिलो', 'पटक', 'हो', 'योसँगै'],
 ['पटक', 'हो', 'योसँगै', 'भारत'],
 ['हो', 'योसँगै', 'भारत', 'कोरोना'],
 ['योसँगै', 'भारत', 'कोरोना', 'भाइरस'],
 ['भारत', 'कोरोना', 'भाइरस', 'संक्रमित'],
 ['कोरोना', 'भाइरस', 'संक्रमित', 'हुने'],
 ['भाइरस', 'संक्रमित', 'हुने', 'संख्या'],
 ['संक्रमित', 'हुने', 'संख्या', 'लाख'],
 ['हुने', 'संख्या', 'लाख', 'हजार'],
 ['संख्या', 'लाख', 'हजार', 'सय'],
 ['लाख', 'हजार', 'सय', 'पुगे'],
 ['हजार', 'सय', 'पुगे', 'छ'],
 ['सय', 'पुगे', 'छ', 'त्यस्तै'],
 ['पुगे', 'छ', 'त्यस्तै', 'पछिल्लो'],
 ['छ', 'त्यस्तै', 'पछिल्लो', 'घण्टा'],
 ['त्यस्तै', 'पछिल्लो', 'घण्टा', 'कोरोना'],
 ['पछिल्लो', 'घण्टा', 'कोरोना', 'थप'],
 ['घण्टा', 'कोरोना', 'थप', 'एक'],
 [

In [ ]:
''' Convert words of text_sequences to Numerical representation '''

tokenizer = Tokenizer()

tokenizer.fit_on_texts(text_sequences)

In [ ]:
sequences = tokenizer.texts_to_sequences(text_sequences)

print(sequences)

[[14, 102, 100, 50], [102, 100, 50, 15], [100, 50, 15, 8], [50, 15, 8, 31], [15, 8, 31, 9], [8, 31, 9, 51], [31, 9, 51, 52], [9, 51, 52, 53], [51, 52, 53, 32], [52, 53, 32, 54], [53, 32, 54, 14], [32, 54, 14, 5], [54, 14, 5, 55], [14, 5, 55, 56], [5, 55, 56, 16], [55, 56, 16, 15], [56, 16, 15, 17], [16, 15, 17, 10], [15, 17, 10, 33], [17, 10, 33, 34], [10, 33, 34, 1], [33, 34, 1, 57], [34, 1, 57, 58], [1, 57, 58, 35], [57, 58, 35, 5], [58, 35, 5, 59], [35, 5, 59, 6], [5, 59, 6, 10], [59, 6, 10, 60], [6, 10, 60, 18], [10, 60, 18, 9], [60, 18, 9, 1], [18, 9, 1, 61], [9, 1, 61, 14], [1, 61, 14, 5], [61, 14, 5, 8], [14, 5, 8, 18], [5, 8, 18, 16], [8, 18, 16, 15], [18, 16, 15, 10], [16, 15, 10, 33], [15, 10, 33, 34], [10, 33, 34, 1], [33, 34, 1, 5], [34, 1, 5, 8], [1, 5, 8, 62], [5, 8, 62, 14], [8, 62, 14, 63], [62, 14, 63, 64], [14, 63, 64, 36], [63, 64, 36, 65], [64, 36, 65, 32], [36, 65, 32, 5], [65, 32, 5, 66], [32, 5, 66, 67], [5, 66, 67, 19], [66, 67, 19, 36], [67, 19, 36, 37], [19, 3

In [ ]:
tokenizer.word_counts

OrderedDict([('भारत', 13),
             ('एकैदिन', 2),
             ('यति', 3),
             ('धेरै', 4),
             ('संख्या', 12),
             ('संक्रमण', 16),
             ('पुष्टि', 8),
             ('भए', 16),
             ('यो', 4),
             ('पहिलो', 4),
             ('पटक', 4),
             ('हो', 8),
             ('योसँगै', 4),
             ('कोरोना', 20),
             ('भाइरस', 4),
             ('संक्रमित', 4),
             ('हुने', 12),
             ('लाख', 12),
             ('हजार', 16),
             ('सय', 8),
             ('पुगे', 8),
             ('छ', 44),
             ('त्यस्तै', 4),
             ('पछिल्लो', 4),
             ('घण्टा', 8),
             ('थप', 4),
             ('एक', 20),
             ('जना', 4),
             ('मृत्यु', 12),
             ('अहिलेसम्म', 4),
             ('हिसाब', 4),
             ('विश्व', 4),
             ('तेस्रो', 4),
             ('प्रभावित', 8),
             ('मुलुक', 4),
             ('महामारी', 4),
             ('सबैभन्दा', 4

In [ ]:
'''We will calculate the vocabulary_size by using the length extracted from tokenizer.word_index and then add 1 to it. 
    We are adding 1 because 0 is a reserved for padding and we want to start our count from 1.'''

vocabulary_size = len(tokenizer.word_counts)+1

In [ ]:
''' We need numpy 2D array as input and output for LSTM '''

n_sequences = np.empty([len(sequences),train_len], dtype='int32')

print(n_sequences)

[[  202473472           0 -1624210624       32755]
 [-1623650712       32755  1117541896       32755]
 [-1623755744       32755 -1623755464       32755]
 [  951048096       32755 -1622860352       32755]
 [-1623755744       32755 -1623113680       32755]
 [  961589296       32755 -1623650712       32755]
 [ 1117529552       32755 -1623755744       32755]
 [-1623755464       32755   951047704       32755]
 [-1622860352       32755 -1623755744       32755]
 [-1623113680       32755   961574192       32755]
 [-1623650712       32755  1117542336       32755]
 [-1623755744       32755 -1623755464       32755]
 [  959807928       32755 -1622860352       32755]
 [-1623755744       32755 -1623113680       32755]
 [  961573168       32755 -1623650712       32755]
 [ 1117542864       32755 -1623755744       32755]
 [-1623755464       32755   959810784       32755]
 [-1622860352       32755 -1623755744       32755]
 [-1623113680       32755   961576368       32755]
 [-1623650712       32755  1117

In [ ]:
n_sequences = np.empty([len(sequences),train_len], dtype='int32')
for i in range(len(sequences)):
    n_sequences[i] = sequences[i]

print(n_sequences)

[[ 14 102 100  50]
 [102 100  50  15]
 [100  50  15   8]
 [ 50  15   8  31]
 [ 15   8  31   9]
 [  8  31   9  51]
 [ 31   9  51  52]
 [  9  51  52  53]
 [ 51  52  53  32]
 [ 52  53  32  54]
 [ 53  32  54  14]
 [ 32  54  14   5]
 [ 54  14   5  55]
 [ 14   5  55  56]
 [  5  55  56  16]
 [ 55  56  16  15]
 [ 56  16  15  17]
 [ 16  15  17  10]
 [ 15  17  10  33]
 [ 17  10  33  34]
 [ 10  33  34   1]
 [ 33  34   1  57]
 [ 34   1  57  58]
 [  1  57  58  35]
 [ 57  58  35   5]
 [ 58  35   5  59]
 [ 35   5  59   6]
 [  5  59   6  10]
 [ 59   6  10  60]
 [  6  10  60  18]
 [ 10  60  18   9]
 [ 60  18   9   1]
 [ 18   9   1  61]
 [  9   1  61  14]
 [  1  61  14   5]
 [ 61  14   5   8]
 [ 14   5   8  18]
 [  5   8  18  16]
 [  8  18  16  15]
 [ 18  16  15  10]
 [ 16  15  10  33]
 [ 15  10  33  34]
 [ 10  33  34   1]
 [ 33  34   1   5]
 [ 34   1   5   8]
 [  1   5   8  62]
 [  5   8  62  14]
 [  8  62  14  63]
 [ 62  14  63  64]
 [ 14  63  64  36]
 [ 63  64  36  65]
 [ 64  36  65  32]
 [ 36  65  3

In [ ]:
''' Here if we do n_sequences[:-1] we get (1391, 4) where the org size was(1392,4) it mean we donot include last row.So
    To get only 3 columns n_sequences[:,:-1]'''

train_inputs = n_sequences[:,:-1]

train_inputs

array([[ 14, 102, 100],
       [102, 100,  50],
       [100,  50,  15],
       [ 50,  15,   8],
       [ 15,   8,  31],
       [  8,  31,   9],
       [ 31,   9,  51],
       [  9,  51,  52],
       [ 51,  52,  53],
       [ 52,  53,  32],
       [ 53,  32,  54],
       [ 32,  54,  14],
       [ 54,  14,   5],
       [ 14,   5,  55],
       [  5,  55,  56],
       [ 55,  56,  16],
       [ 56,  16,  15],
       [ 16,  15,  17],
       [ 15,  17,  10],
       [ 17,  10,  33],
       [ 10,  33,  34],
       [ 33,  34,   1],
       [ 34,   1,  57],
       [  1,  57,  58],
       [ 57,  58,  35],
       [ 58,  35,   5],
       [ 35,   5,  59],
       [  5,  59,   6],
       [ 59,   6,  10],
       [  6,  10,  60],
       [ 10,  60,  18],
       [ 60,  18,   9],
       [ 18,   9,   1],
       [  9,   1,  61],
       [  1,  61,  14],
       [ 61,  14,   5],
       [ 14,   5,   8],
       [  5,   8,  18],
       [  8,  18,  16],
       [ 18,  16,  15],
       [ 16,  15,  10],
       [ 15,  10

In [ ]:
''' n_sequences[:,-1] incldue all row value with last column value '''

train_targets = n_sequences[:,-1]

print(len(train_targets))
print(train_targets)

210
[ 50  15   8  31   9  51  52  53  32  54  14   5  55  56  16  15  17  10
  33  34   1  57  58  35   5  59   6  10  60  18   9   1  61  14   5   8
  18  16  15  10  33  34   1   5   8  62  14  63  64  36  65  32   5  66
  67  19  36  37  11  68  17  69  19   8  31   9   1  37  70  71   6  17
  10  18  72   1  12  73  19  74   9  75  76  11  38  77  78   2  20  79
   3  16   4  21  39  40  13  80   1  13  81  82  41  42  43  44  83   2
  45  20  46   3   4   1  22  23   7  24  25  26   7   6  27  28   2  12
  29   3  47   4   1  84  85  38  41  42  43  44  86   2  45  20  46   3
   4   1  22  23  26  25  24   7   6  27  28   2  12  29   3  47   4  21
  13  11  30  48  87  39  40  88  89   1  90  35  11  30  91  92  30  93
  49  49  94  95  96  48  97  13  12   1  22  23   7  24  25  26   7   6
  27  28   2  29   3   4  21  98  99 101 103 104]


In [ ]:
''' One hot Encoding of the target value '''

train_targets = to_categorical(train_targets, num_classes=vocabulary_size)
train_targets

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [ ]:
train_inputs.shape

(1392, 3)

In [ ]:
train_inputs.shape[1]


3

In [ ]:
''' Length of all the target value for all training data '''

len(train_targets)

1392

In [ ]:
''' Each target value consist of the 455 unique words OR Predication '''

len(train_targets[0])

455

In [ ]:
train_targets[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
seq_len = train_inputs.shape[1]

# Model Building

In [109]:
from keras.models import Sequential, load_model
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
#model = load_model("mymodel.h5")

model = Sequential()
model.add(Embedding(vocabulary_size, seq_len, input_length=seq_len))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(50,activation='relu'))
model.add(Dense(vocabulary_size, activation='softmax'))
print(model.summary())
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_inputs,train_targets,epochs=500,verbose=1)
model.save("/content/drive/My Drive/Sequence Models/next_word_suggestor/LSTM/Nepmodel_stemming.h5")

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 3, 3)              315       
_________________________________________________________________
lstm_4 (LSTM)                (None, 3, 50)             10800     
_________________________________________________________________
lstm_5 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_4 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_5 (Dense)              (None, 105)               5355      
Total params: 39,220
Trainable params: 39,220
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/500
7/7 [==============================] - 0s 5ms/step - loss: 4.6538 - accuracy: 0.0143
Epoch 2/500
7/

# Nepali text predication

In [110]:
input_text = input()

भारतमा एकैदिन यति


In [111]:
input_text

'भारतमा एकैदिन यति'

In [112]:
x=input_text.strip().split()

In [119]:
x

['भारतमा', 'एकैदिन', 'यति']

In [115]:
z=[stemword(y) for y in x]

In [116]:
z

['भारत', 'एकैदिन', 'यति']

In [118]:
" ".join(z)

'भारत एकैदिन यति'

In [120]:
from keras.preprocessing.sequence import pad_sequences
input_text = input().strip().split()
z=[stemword(y) for y in input_text]
input_text= " ".join(z)
encoded_text = tokenizer.texts_to_sequences([input_text])[0]
pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
print(encoded_text, pad_encoded)
for i in (model.predict(pad_encoded)[0]).argsort()[-3:][::-1]:
  pred_word = tokenizer.index_word[i]
  print("Next word suggestion:",pred_word)

भारतमा एकैदिन यति
[14, 102, 100] [[ 14 102 100]]
Next word suggestion: धेरै
Next word suggestion: मृत्यु
Next word suggestion: जारी
